# Generated by Django 3.2.8 on 2022-05-19 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название языка')),
            ],
            options={
                'verbose_name': 'язык',
                'verbose_name_plural': 'языки',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название навыка')),
            ],
            options={
                'verbose_name': 'навык',
                'verbose_name_plural': 'навыки',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, verbose_name='Имя')),
                ('surname', models.CharField(max_length=36, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=36, verbose_name='Отчество')),
                ('hobbies', models.CharField(blank=True, max_length=1000, verbose_name='Увлечения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('avatar', models.ImageField(blank=True, upload_to='photos/', verbose_name='Фото профиля')),
                ('languages', models.ManyToManyField(to='app_candidates.Language')),
                ('skills', models.ManyToManyField(to='app_candidates.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'кандидат',
                'verbose_name_plural': 'кандидаты',
            },
        ),
    ]
