# Generated by Django 3.2.8 on 2022-05-20 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_candidates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='name',
            new_name='language_name',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='skill_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='avatar',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/', verbose_name='Фото')),
                ('candidate', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='app_candidates.candidate', verbose_name='Кандидат')),
            ],
            options={
                'verbose_name': 'фотография',
                'verbose_name_plural': 'фотографии',
            },
        ),
    ]
